### ISSUE TITLE
Action senders data sends only the first value :P

### ISSUE THREAD

**Issue by louire** [AriDevK/MySnippetToolkit#1]
<h1>Idk why, production's down, help!!!!</h1> 

![image](https://github.com/AriDevK/MySnippetToolkit/assets/71304021/f8ed099c-b039-4f1d-a875-865f69934f6d)

![communistCat](https://media.tenor.com/vKctrvaXe74AAAAM/comunism.gif)

**Comment by AriDevK** [comment]
At the render function (fromArray) there is a JS script that is added to each button; maybe there is the problem, im gonna check

<img src="https://c.tenor.com/9psBq90oFfwAAAAd/tenor.gif" />

**Comment by AriDevK** [comment]
Is at the $onClick var, we need to debug this method

```php
public static function action(string $caption, string $onClick, string $cssClass = null, string $eventAlias = null): string
    {
        $eventAlias = $eventAlias == null ? "undefined" : $eventAlias;
        $onClick = str_replace("'", "\"", $onClick);
        $onClick = '(function(s, e="' . $eventAlias . '"){' . $onClick . '})(
            {
                id: this.id, 
                row : parseInt(attr(this, "row")),
                data : [...tbl(this).tHead.rows[0].cells].map(h => h.innerText).slice(0, -1).reduce((a, key, i) => {
                    return {...a, [key]: tbl(this).rows[parseInt(attr(this, "row"))].cells[0].innerText}
                }, {})
            })';
        return "input type='button' value='" . $caption . "' class='" . $cssClass . "' onclick='" . $onClick . "'";
    }
```

**Comment by ArthurDaKing3** [comment]
It may be something wrong inside the loop that sets the sender data 🍜

![cat](https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExMDRpbGRjemtjb21oZ3ZreDM5N2poa3FudnRqZnc1MXgxZTJxdnZ4YyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/nR4L10XlJcSeQ/giphy.gif)

**Comment by louire** [comment]
<h1> the motherland appreciates it </h1>

![communistCat](https://i.imgflip.com/42k41q.png?a472176)
